#
# https://github.com/naudio/NAudio/blob/fb35ce8367f30b8bc5ea84e7d2529e172cf4c381/NAudio.Core/Manufacturers.cs
#
# Manufacturer codes from mmreg.h
#

1=Microsoft Corporation
2=Creative Labs, Inc.
3=Media Vision, Inc.
4=Fujitsu, Ltd.
20=Artisoft, Inc.
21=Turtle Beach Systems
22=International Business Machines
23=VocalTec, Inc.
24=Roland Corporation
25=DSP Solutions, Inc.
26=NEC Corporation
27=ATI Technologies, Inc.
28=Wang Laboratories
29=Tandy Corporation
30=Voyetra Technologies
31=Antex Electronics Corporation
32=ICL Personal Systems
33=Intel Corporation
34=Advanced Gravis Computer Technology, Ltd.
35=Video Associates Labs, Inc.
36=InterActive, Inc.
37=Yamaha Corporation of America
38=Everex Systems, Inc.
39=Echo Speech Corporation
40=Sierra Semiconductor Corporation
41=Computer Aided Technology, Inc.
42=APPS Software
43=DSP Group, Inc.
44=microEngineering Labs
45=Computer Friends, Inc.
46=ESS Technology, Inc.
47=Audio, Inc.
48=Motorola, Inc.
49=Canopus, Co., Ltd.
50=Seiko Epson Corporation, Inc.
51=Truevision, Inc.
52=Aztech Labs, Inc.
53=VideoLogic, Inc.
54=SCALACS
55=Toshihiko Okuhura, Korg, Inc.
56=Audio Processing Technology
57=Integrated Circuit Systems, Inc.
58=Iterated Systems, Inc.
59=Metheus Corporation
60=Logitech, Inc.
61=Winnov, LP
62=NCR Corporation
63=EXAN, Ltd.
64=AST Research, Inc.
65=Willow Pond Corporation
66=Sonic Foundry
67=Visual Information Technologies, Inc.
68=MOSCOM Corporation
69=Silicon Software, Inc.
73=Supermac Technology, Inc.
74=Audio Processing Technology
76=Speech Compression
77=Ahead, Inc
78=Dolby Laboratories, Inc.
79=OKI
80=Auravision Corporation
81=Ing. C. Olivetti & C., s.p.a.
82=I/O Magic Corporation
83=Matsushita Electric Corporation of America
84=Control Resources Corporation
85=Xebec Multimedia Solutions Limited
86=New Media Corporation
87=Natural MicroSystems Corporation
88=Lyrrus, Inc.
89=Compusic
90=OPTi, Inc.
91=Adlib Accessories Inc.
92=Compaq Computer Corp
93=Dialogic Corporation
94=Insoft
95=M.p. Technologies, Inc.
96=Weitek
97=Lernout & Hauspie
98=Quanta Computer Inc.
99=Apple Computer, Inc.
100=Digital Equipment Corporation
101=Mark of the Unicorn
102=Workbit Corporation
103=Ositech Communications Inc.
104=miro Computer Products AG
105=Cirrus Logic
106=ISOLUTION  B.V.
107=Horizons Technology, Inc
108=Computer Concepts Ltd
109=Voice Technologies Group, Inc.
110=Radius
111=Rockwell International
112=Co. XYZ for testing
113=Opcode Systems
114=Voxware Inc
115=Northern Telecom Limited
116=APICOM
117=Grande Software
118=ADDX
119=Wildcat Canyon Software
120=Rhetorex Inc
121=Brooktree Corporation
125=ENSONIQ Corporation
126=FAST Multimedia AG
127=NVidia Corporation
128=OKSORI Co., Ltd.
129=DiAcoustics, Inc.
130=Gulbransen, Inc.
131=Kay Elemetrics, Inc.
132=Crystal Semiconductor Corporation
133=Splash Studios
134=Quarterdeck Corporation
135=TDK Corporation
136=Digital Audio Labs, Inc.
137=Seer Systems, Inc.
138=PictureTel Corporation
139=AT&T Microelectronics
140=Osprey Technologies, Inc.
141=Mediatrix Peripherals
142=SounDesignS M.C.s. Ltd.
143=a.L. Digital Ltd.
144=Spectrum Signal Processing, Inc.
145=Electronic Courseware Systems, Inc.
146=AMD
147=Core Dynamics
148=CANAM Computers
149=Softsound, Ltd.
150=Norris Communications, Inc.
151=Danka data Devices
152=EuPhonics
153=Precept Software, Inc.
154=Crystal Net Corporation
155=Chromatic Research, Inc
156=Voice Information Systems, Inc
157=Vienna Systems
158=Connectix Corporation
159=Gadget Labs LLC
160=Frontier Design Group LLC
161=Viona Development GmbH
162=Casio Computer Co., LTD
163=Diamond Multimedia
164=S3
172=Fraunhofer
