//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

package mdplayer.properties;

import java.awt.image.BufferedImage;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.Icon;


/**
 * ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
 */
// このクラスは StronglyTypedResourceBuilder クラスが ResGen
// または Visual Studio のようなツールを使用して自動生成されました。
// メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
// ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
//@System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
//@System.Diagnostics.DebuggerNonUserCodeAttribute()]
//@System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Resources {

    private static ResourceBundle resourceMan;

    private static Locale resourceCulture;

    //@System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    private Resources() {
    }

    /**
     * このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
     */
    //@System.ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)]
    public static ResourceBundle getResourceManager() {

        if (resourceMan ==  null) {
            ResourceBundle temp = ResourceBundle.getBundle("mdplayer.Properties.Resources");
            resourceMan = temp;
        }
        return resourceMan;
    }

    /**
     * すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
     * 現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
     */
    //@System.ComponentModel.EditorBrowsableAttribute(ComponentModel.EditorBrowsableState.Advanced)]
    public static Locale getCulture() {

        return resourceCulture;
    }

    void setCulture(Locale value) {
        resourceCulture = value;
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getaddFolderPL() {

        Object obj = resourceMan.getObject("addFolderPL");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getaddPL() {

        Object obj = resourceMan.getObject("addPL");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccFadeout() {

        Object obj = resourceMan.getObject("ccFadeout");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccFast() {

        Object obj = resourceMan.getObject("ccFast");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccInformation() {

        Object obj = resourceMan.getObject("ccInformation");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccKBD() {

        Object obj = resourceMan.getObject("ccKBD");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccLoop() {

        Object obj = resourceMan.getObject("ccLoop");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccLoopOne() {

        Object obj = resourceMan.getObject("ccLoopOne");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccMIDIKBD() {

        Object obj = resourceMan.getObject("ccMIDIKBD");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccMixer() {

        Object obj = resourceMan.getObject("ccMixer");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccNext() {

        Object obj = resourceMan.getObject("ccNext");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccOpenFolder() {

        Object obj = resourceMan.getObject("ccOpenFolder");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccPause() {

        Object obj = resourceMan.getObject("ccPause");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccPlay() {

        Object obj = resourceMan.getObject("ccPlay");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccPlayList() {

        Object obj = resourceMan.getObject("ccPlayList");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccPrevious() {

        Object obj = resourceMan.getObject("ccPrevious");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccRandom() {

        Object obj = resourceMan.getObject("ccRandom");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccSetting() {

        Object obj = resourceMan.getObject("ccSetting");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccSlow() {

        Object obj = resourceMan.getObject("ccSlow");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccStep() {

        Object obj = resourceMan.getObject("ccStep");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccStop() {

        Object obj = resourceMan.getObject("ccStop");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccVST() {

        Object obj = resourceMan.getObject("ccVST");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getccZoom() {

        Object obj = resourceMan.getObject("ccZoom");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchFadeout() {

        Object obj = resourceMan.getObject("chFadeout");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchFast() {

        Object obj = resourceMan.getObject("chFast");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchInformation() {

        Object obj = resourceMan.getObject("chInformation");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchKBD() {

        Object obj = resourceMan.getObject("chKBD");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchLoop() {

        Object obj = resourceMan.getObject("chLoop");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchLoopOne() {

        Object obj = resourceMan.getObject("chLoopOne");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchMIDIKBD() {

        Object obj = resourceMan.getObject("chMIDIKBD");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchMixer() {

        Object obj = resourceMan.getObject("chMixer");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchNext() {

        Object obj = resourceMan.getObject("chNext");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchOpenFolder() {

        Object obj = resourceMan.getObject("chOpenFolder");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchPause() {

        Object obj = resourceMan.getObject("chPause");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchPlay() {

        Object obj = resourceMan.getObject("chPlay");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchPlayList() {

        Object obj = resourceMan.getObject("chPlayList");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchPrevious() {

        Object obj = resourceMan.getObject("chPrevious");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchRandom() {

        Object obj = resourceMan.getObject("chRandom");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchSetting() {

        Object obj = resourceMan.getObject("chSetting");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchSlow() {

        Object obj = resourceMan.getObject("chSlow");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchStep() {

        Object obj = resourceMan.getObject("chStep");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchStop() {

        Object obj = resourceMan.getObject("chStop");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchVST() {

        Object obj = resourceMan.getObject("chVST");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getchZoom() {

        Object obj = resourceMan.getObject("chZoom");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciFadeout() {

        Object obj = resourceMan.getObject("ciFadeout");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciFast() {

        Object obj = resourceMan.getObject("ciFast");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciInformation() {

        Object obj = resourceMan.getObject("ciInformation");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciKBD() {

        Object obj = resourceMan.getObject("ciKBD");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciLoop() {

        Object obj = resourceMan.getObject("ciLoop");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciLoopOne() {

        Object obj = resourceMan.getObject("ciLoopOne");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciMIDIKBD() {

        Object obj = resourceMan.getObject("ciMIDIKBD");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciMixer() {

        Object obj = resourceMan.getObject("ciMixer");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciNext() {

        Object obj = resourceMan.getObject("ciNext");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciOpenFolder() {

        Object obj = resourceMan.getObject("ciOpenFolder");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciPause() {

        Object obj = resourceMan.getObject("ciPause");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciPlay() {

        Object obj = resourceMan.getObject("ciPlay");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciPlayList() {

        Object obj = resourceMan.getObject("ciPlayList");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciPrevious() {

        Object obj = resourceMan.getObject("ciPrevious");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciRandom() {

        Object obj = resourceMan.getObject("ciRandom");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciSetting() {

        Object obj = resourceMan.getObject("ciSetting");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciSlow() {

        Object obj = resourceMan.getObject("ciSlow");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciStep() {

        Object obj = resourceMan.getObject("ciStep");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciStop() {

        Object obj = resourceMan.getObject("ciStop");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciVST() {

        Object obj = resourceMan.getObject("ciVST");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getciZoom() {

        Object obj = resourceMan.getObject("ciZoom");
        return ((BufferedImage) (obj));
    }

    /**
     * MDPlayer
     * VGMファイルなどのPlayer(メガドライブ音源チップなどのエミュレーションによる演奏ツール)
     *
     * [概要]
     * このツールは、鍵盤表示を行いながらVGMファイルの再生を行います。
     * (NRD,XGM,S98,MID,RCP,NSF,HES,Sid,MDR,MDX,MND,MUC(TBD),MUB(TBD)ファイルにも対応。)
     *
     * [注意]
     *  ・再生時の音量に注意してください。バグによる雑音が大音量で再生される場合もあります。
     *  (特に再生したことのないファイルを試す場合や、プログラムを更新した場合。)
     *
     *  ・使用中に不具合を見つけた場合はお手数ですがTwitter(@kumakumakumaT_T)までご連絡ください。
     *  (VGMPlayやNRTDRV、その他素晴らしいソフトウェアの作者様方に、
     *  直接MDPlayerについての連絡がいくことの無い様にお願いします。)
     *  できるかぎり対応させていただくつもりですが、ご希望に添えないことも多々あります。ご了承ください。
     *
     * [対応フォーマ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getCntDescription() {

        return resourceMan.getString("cntDescription");
    }

    /**
     * 例外発生:\n- Type ------\n%d\n- Message ------\n%d\n- Source ------\n%d\n- StackTrace ------\n%d\n に類似しているローカライズされた文字列を検索します。
     */
    public static String getCntExceptionFormat() {

        return resourceMan.getString("cntExceptionFormat");
    }

    /**
     * 内部例外:\n- Type ------\n%d\n- Message ------\n%d\n- Source ------\n%d\n- StackTrace ------\n%d\n に類似しているローカライズされた文字列を検索します。
     */
    public static String getcntInnerExceptionFormat() {

        return resourceMan.getString("cntInnerExceptionFormat");
    }

    /**
     * Log.txt に類似しているローカライズされた文字列を検索します。
     */
    public static String getCntLogFilename() {

        return resourceMan.getString("cntLogFilename");
    }

    /**
     * Setting.xml に類似しているローカライズされた文字列を検索します。
     */
    public static String getcntSettingFileName() {

        return resourceMan.getString("cntSettingFileName");
    }

    /**
     * VGMファイル(*.Vgm;*.vgz)|*.Vgm;*.vgz|
     * XGMファイル(*.Xgm)|*.Xgm|
     * ZGMファイル(*.Zgm)|*.Zgm|
     * HESファイル(*.Hes)|*.Hes|
     * MDRファイル(*.mdr)|*.mdr|
     * MDXファイル(*.mdx)|*.mdx|
     * MGSファイル(*.mgs)|*.mgs|
     * MNDファイル(*.mnd)|*.mnd|
     * MUCOM88ファイル(*.mub;*.muc)|*.mub;*.muc|
     * NRDファイル(*.nrd)|*.nrd|
     * NSFファイル(*.Nsf)|*.Nsf|
     * PMDファイル(*.m;*.m2;*.mz;*.mml)|*.m;*.m2;*.mz;*.mml|
     * RCPファイル(*.rcp)|*.rcp|
     * S98ファイル(*.s98)|*.s98|
     * SIDファイル(*.Sid)|*.Sid|
     * StandardMIDIファイル(*.mid)|*.mid|
     * WAVファイル(*.wav)|*.wav|
     * MP3ファイル(*.mp3)|*.mp3|
     * AIFFファイル(*.aiff)|*.aiff|
     * M3Uファイル [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getCntSupportFile() {

        return resourceMan.getString("cntSupportFile");
    }

    /**
     * yyyy/MM/dd HH:mm:ss     に類似しているローカライズされた文字列を検索します。
     */
    public static String getCntTimeFormat() {

        return resourceMan.getString("cntTimeFormat");
    }

    /**
     * &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
     * &lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
     * &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
     * &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
     * &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
     * &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
     * &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
     * &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
     * &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
     * &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
     * &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
     * &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getDefaultVolumeBalance_HES() {

        return resourceMan.getString("DefaultVolumeBalance_HES");
    }

    /**
     * &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
     * &lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
     * &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
     * &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
     * &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
     * &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
     * &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
     * &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
     * &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
     * &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
     * &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
     * &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getDefaultVolumeBalance_MDR() {

        return resourceMan.getString("DefaultVolumeBalance_MDR");
    }

    /**
     * &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
     * &lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
     * &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
     * &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
     * &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
     * &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
     * &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
     * &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
     * &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
     * &lt;OKIM6258Volume&gt;0&lt;/OKIM6258Volume&gt;
     * &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
     * &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCMVol [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getDefaultVolumeBalance_MDX() {

        return resourceMan.getString("DefaultVolumeBalance_MDX");
    }

    /**
     * &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
     * &lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
     * &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
     * &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
     * &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
     * &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
     * &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
     * &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
     * &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
     * &lt;OKIM6258Volume&gt;0&lt;/OKIM6258Volume&gt;
     * &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
     * &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCMVol [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getDefaultVolumeBalance_MND() {

        return resourceMan.getString("DefaultVolumeBalance_MND");
    }

    /**
     * &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
     * &lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
     * &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
     * &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
     * &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
     * &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
     * &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
     * &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
     * &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
     * &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
     * &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
     * &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getDefaultVolumeBalance_MUB() {

        return resourceMan.getString("DefaultVolumeBalance_MUB");
    }

    /**
     * &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
     * &lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
     * &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
     * &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
     * &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
     * &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
     * &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
     * &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
     * &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
     * &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
     * &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
     * &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getDefaultVolumeBalance_MUC() {

        return resourceMan.getString("DefaultVolumeBalance_MUC");
    }

    /**
     * &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
     * &lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
     * &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
     * &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
     * &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
     * &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
     * &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
     * &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
     * &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
     * &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
     * &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
     * &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getDefaultVolumeBalance_NRT() {

        return resourceMan.getString("DefaultVolumeBalance_NRT");
    }

    /**
     * &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
     * &lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
     * &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
     * &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
     * &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
     * &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
     * &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
     * &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
     * &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
     * &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
     * &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
     * &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getDefaultVolumeBalance_NSF() {

        return resourceMan.getString("DefaultVolumeBalance_NSF");
    }

    /**
     * &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
     * &lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
     * &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
     * &lt;YM2612Volume&gt;0&lt;/YM2612Volume&gt;
     * &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
     * &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
     * &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
     * &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
     * &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
     * &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
     * &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
     * &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCMVol [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getDefaultVolumeBalance_S98() {

        return resourceMan.getString("DefaultVolumeBalance_S98");
    }

    /**
     * &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
     * &lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
     * &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
     * &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
     * &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
     * &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
     * &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
     * &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
     * &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
     * &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
     * &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
     * &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getDefaultVolumeBalance_SID() {

        return resourceMan.getString("DefaultVolumeBalance_SID");
    }

    /**
     * &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
     * &lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
     * &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
     * &lt;YM2612Volume&gt;0&lt;/YM2612Volume&gt;
     * &lt;SN76489Volume&gt;0&lt;/SN76489Volume&gt;
     * &lt;RF5C68Volume&gt;0&lt;/RF5C68Volume&gt;
     * &lt;RF5C164Volume&gt;0&lt;/RF5C164Volume&gt;
     * &lt;PWMVolume&gt;0&lt;/PWMVolume&gt;
     * &lt;C140Volume&gt;0&lt;/C140Volume&gt;
     * &lt;OKIM6258Volume&gt;0&lt;/OKIM6258Volume&gt;
     * &lt;OKIM6295Volume&gt;0&lt;/OKIM6295Volume&gt;
     * &lt;SEGAPCMVolume&gt;0&lt;/SEGAPCMVolume&gt;
     * &lt;AY8910Volume&gt;0&lt; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getDefaultVolumeBalance_VGM() {

        return resourceMan.getString("DefaultVolumeBalance_VGM");
    }

    /**
     * &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
     * &lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
     * &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
     * &lt;YM2612Volume&gt;0&lt;/YM2612Volume&gt;
     * &lt;SN76489Volume&gt;-15&lt;/SN76489Volume&gt;
     * &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
     * &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
     * &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
     * &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
     * &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
     * &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
     * &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCMVolu [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getDefaultVolumeBalance_XGM() {

        return resourceMan.getString("DefaultVolumeBalance_XGM");
    }

    /**
     * &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
     * &lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
     * &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
     * &lt;YM2612Volume&gt;0&lt;/YM2612Volume&gt;
     * &lt;SN76489Volume&gt;-15&lt;/SN76489Volume&gt;
     * &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
     * &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
     * &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
     * &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
     * &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
     * &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
     * &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCMVolu [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
     */
    public static String getDefaultVolumeBalance_ZGM() {

        return resourceMan.getString("DefaultVolumeBalance_ZGM");
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getDownPL() {

        Object obj = resourceMan.getObject("downPL");
        return ((BufferedImage) (obj));
    }

    /**
     * (アイコン) に類似した型 Icon のローカライズされたリソースを検索します。
     */
    public static Icon getFeli128() {

        Object obj = resourceMan.getObject("Feli128");
        return ((Icon) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getFeliAndMD2() {

        Object obj = resourceMan.getObject("FeliAndMD2");
        return ((BufferedImage) (obj));
    }

    /**
     * (アイコン) に類似した型 Icon のローカライズされたリソースを検索します。
     */
    public static Icon getFeliTop() {

        Object obj = resourceMan.getObject("FeliTop");
        return ((Icon) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getimgPL() {

        Object obj = resourceMan.getObject("imgPL");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getjapPL() {

        Object obj = resourceMan.getObject("japPL");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getmmlPL() {

        Object obj = resourceMan.getObject("mmlPL");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getopenPL() {

        Object obj = resourceMan.getObject("openPL");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplane() {

        Object obj = resourceMan.getObject("plane");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneAY8910() {

        Object obj = resourceMan.getObject("planeAY8910");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneB() {

        Object obj = resourceMan.getObject("planeB");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getPlaneC() {

        Object obj = resourceMan.getObject("planeC");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneC352() {

        Object obj = resourceMan.getObject("planeC352");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getPlaneControl() {

        Object obj = resourceMan.getObject("planeControl");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getPlaneD() {

        Object obj = resourceMan.getObject("planeD");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneDMG() {

        Object obj = resourceMan.getObject("planeDMG");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneE() {

        Object obj = resourceMan.getObject("planeE");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getPlaneF() {

        Object obj = resourceMan.getObject("planeF");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneFDS() {

        Object obj = resourceMan.getObject("planeFDS");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneHuC6280() {

        Object obj = resourceMan.getObject("planeHuC6280");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneK051649() {

        Object obj = resourceMan.getObject("planeK051649");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneMIDI_GM() {

        Object obj = resourceMan.getObject("planeMIDI_GM");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneMIDI_GS() {

        Object obj = resourceMan.getObject("planeMIDI_GS");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneMIDI_XG() {
        Object obj = resourceMan.getObject("planeMIDI_XG");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneMixer() {
        Object obj = resourceMan.getObject("planeMixer");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneMMC5() {

        Object obj = resourceMan.getObject("planeMMC5");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneMSM6258() {

        Object obj = resourceMan.getObject("planeMSM6258");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneMSM6295() {

        Object obj = resourceMan.getObject("planeMSM6295");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneMultiPCM() {

        Object obj = resourceMan.getObject("planeMultiPCM");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneN106() {

        Object obj = resourceMan.getObject("planeN106");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneNESDMC() {

        Object obj = resourceMan.getObject("planeNESDMC");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplanePPZ8() {

        Object obj = resourceMan.getObject("planePPZ8");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getPlaneQSound() {

        Object obj = resourceMan.getObject("planeQSound");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneS5B() {

        Object obj = resourceMan.getObject("planeS5B");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneSEGAPCM() {

        Object obj = resourceMan.getObject("planeSEGAPCM");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneSN76489() {

        Object obj = resourceMan.getObject("planeSN76489");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneVRC6() {

        Object obj = resourceMan.getObject("planeVRC6");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneVRC7() {

        Object obj = resourceMan.getObject("planeVRC7");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneY8950() {

        Object obj = resourceMan.getObject("planeY8950");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneYM2203() {

        Object obj = resourceMan.getObject("planeYM2203");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneYM2413() {

        Object obj = resourceMan.getObject("planeYM2413");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneYM2610() {

        Object obj = resourceMan.getObject("planeYM2610");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneYM2612() {

        Object obj = resourceMan.getObject("planeYM2612");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneYM2612MIDI() {

        Object obj = resourceMan.getObject("planeYM2612MIDI");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneYM3526() {

        Object obj = resourceMan.getObject("planeYM3526");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneYM3812() {

        Object obj = resourceMan.getObject("planeYM3812");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneYMF262() {

        Object obj = resourceMan.getObject("planeYMF262");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneYMF271() {

        Object obj = resourceMan.getObject("planeYMF271");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneYMF278B() {

        Object obj = resourceMan.getObject("planeYMF278B");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getplaneYMZ280B() {

        Object obj = resourceMan.getObject("planeYMZ280B");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrChipName_01() {

        Object obj = resourceMan.getObject("rChipName_01");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrChipName_02() {

        Object obj = resourceMan.getObject("rChipName_02");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrChipName_03() {

        Object obj = resourceMan.getObject("rChipName_03");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 System.Byte[] のローカライズされたリソースを検索します。
     */
    public static byte[] getREADME() {

        Object obj = resourceMan.getObject("README");
        return ((byte[]) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrFader() {

        Object obj = resourceMan.getObject("rFader");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrFont_01() {

        Object obj = resourceMan.getObject("rFont_01");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrFont_02() {

        Object obj = resourceMan.getObject("rFont_02");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrFont_03() {

        Object obj = resourceMan.getObject("rFont_03");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrFont_04() {

        Object obj = resourceMan.getObject("rFont_04");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrFont_05() {

        Object obj = resourceMan.getObject("rFont_05");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrFont_06() {

        Object obj = resourceMan.getObject("rFont_06");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrKakko_00() {

        Object obj = resourceMan.getObject("rKakko_00");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrKBD_01() {

        Object obj = resourceMan.getObject("rKBD_01");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrKBD_02() {

        Object obj = resourceMan.getObject("rKBD_02");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrKBD_03() {

        Object obj = resourceMan.getObject("rKBD_03");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMenuButtons_01() {

        Object obj = resourceMan.getObject("rMenuButtons_01");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMenuButtons_02() {

        Object obj = resourceMan.getObject("rMenuButtons_02");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_01() {

        Object obj = resourceMan.getObject("rMIDILCD_01");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_02() {

        Object obj = resourceMan.getObject("rMIDILCD_02");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_03() {

        Object obj = resourceMan.getObject("rMIDILCD_03");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_Fader_01() {

        Object obj = resourceMan.getObject("rMIDILCD_Fader_01");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_Fader_02() {

        Object obj = resourceMan.getObject("rMIDILCD_Fader_02");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_Fader_03() {

        Object obj = resourceMan.getObject("rMIDILCD_Fader_03");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_Font_01() {

        Object obj = resourceMan.getObject("rMIDILCD_Font_01");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_Font_02() {

        Object obj = resourceMan.getObject("rMIDILCD_Font_02");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_Font_03() {

        Object obj = resourceMan.getObject("rMIDILCD_Font_03");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_Font_04() {

        Object obj = resourceMan.getObject("rMIDILCD_Font_04");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_Font_05() {

        Object obj = resourceMan.getObject("rMIDILCD_Font_05");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_Font_06() {

        Object obj = resourceMan.getObject("rMIDILCD_Font_06");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_KBD_01() {

        Object obj = resourceMan.getObject("rMIDILCD_KBD_01");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_Vol_01() {

        Object obj = resourceMan.getObject("rMIDILCD_Vol_01");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_Vol_02() {

        Object obj = resourceMan.getObject("rMIDILCD_Vol_02");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrMIDILCD_Vol_03() {

        Object obj = resourceMan.getObject("rMIDILCD_Vol_03");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrNESDMC() {

        Object obj = resourceMan.getObject("rNESDMC");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrPan_01() {

        Object obj = resourceMan.getObject("rPan_01");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrPan_02() {

        Object obj = resourceMan.getObject("rPan_02");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrPan_03() {

        Object obj = resourceMan.getObject("rPan_03");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrPan2_01() {

        Object obj = resourceMan.getObject("rPan2_01");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrPan2_02() {

        Object obj = resourceMan.getObject("rPan2_02");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrPSGEnv() {

        Object obj = resourceMan.getObject("rPSGEnv");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrPSGMode_01() {

        Object obj = resourceMan.getObject("rPSGMode_01");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrPSGMode_02() {

        Object obj = resourceMan.getObject("rPSGMode_02");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrPSGMode_03() {

        Object obj = resourceMan.getObject("rPSGMode_03");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrPSGMode_04() {

        Object obj = resourceMan.getObject("rPSGMode_04");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrPSGMode_05() {

        Object obj = resourceMan.getObject("rPSGMode_05");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrPSGMode_06() {

        Object obj = resourceMan.getObject("rPSGMode_06");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrType_01() {

        Object obj = resourceMan.getObject("rType_01");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrType_02() {

        Object obj = resourceMan.getObject("rType_02");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrType_03() {

        Object obj = resourceMan.getObject("rType_03");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrType_04() {

        Object obj = resourceMan.getObject("rType_04");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrType_05() {

        Object obj = resourceMan.getObject("rType_05");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrType_06() {

        Object obj = resourceMan.getObject("rType_06");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrType_YMF271() {

        Object obj = resourceMan.getObject("rType_YMF271");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrVol_01() {

        Object obj = resourceMan.getObject("rVol_01");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrVol_02() {

        Object obj = resourceMan.getObject("rVol_02");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrVol_03() {

        Object obj = resourceMan.getObject("rVol_03");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrWavGraph() {

        Object obj = resourceMan.getObject("rWavGraph");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getrWavGraph2() {

        Object obj = resourceMan.getObject("rWavGraph2");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getsavePL() {

        Object obj = resourceMan.getObject("savePL");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage gettxtPL() {

        Object obj = resourceMan.getObject("txtPL");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getupPL() {

        Object obj = resourceMan.getObject("upPL");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getVHeight1() {

        Object obj = resourceMan.getObject("vHeight1");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getVHeight2() {

        Object obj = resourceMan.getObject("vHeight2");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getVHeight3() {

        Object obj = resourceMan.getObject("vHeight3");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getVType1() {

        Object obj = resourceMan.getObject("vType1");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getVType2() {

        Object obj = resourceMan.getObject("vType2");
        return ((BufferedImage) (obj));
    }

    /**
     * 型 BufferedImage のローカライズされたリソースを検索します。
     */
    public static BufferedImage getVType3() {

        Object obj = resourceMan.getObject("vType3");
        return ((BufferedImage) (obj));
    }
}
