//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

package mdplayer.properties;


//@System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
//@System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
class Settings {

    private static Settings defaultInstance = new Settings();

    public static Settings getDefault() {
        return defaultInstance;
    }
}
