clmKey.HeaderText=Key
clmSongNo.HeaderText=SongNo
clmZipFileName.HeaderText=ZipFileName
clmFileName.HeaderText=FileName
clmPlayingNow.HeaderText= 
clmPlayingNow.Width=25
clmEXT.HeaderText=EXT
clmEXT.Width=40
clmType.HeaderText=Type
clmType.Width=40
clmTitle.HeaderText=Title
clmTitle.Width=200
clmTitleJ.HeaderText=タイトル
clmDispFileName.HeaderText=FileName
clmGame.HeaderText=Game
clmGame.Width=200
clmGameJ.HeaderText=ゲーム
clmComposer.HeaderText=Composer
clmComposerJ.HeaderText=作曲者
clmVGMby.HeaderText=VGMby
clmConverted.HeaderText=Release
clmNotes.HeaderText=Notes
clmDuration.HeaderText=Duration
clmSpacer.HeaderText=
dgvList.Location=0, 0
tsmiA.Size=83, 22
tsmiA.Text=A
tsmiB.Size=83, 22
tsmiB.Text=B
tsmiC.Size=83, 22
tsmiC.Text=C
tsmiD.Size=83, 22
tsmiD.Text=D
tsmiE.Size=83, 22
tsmiE.Text=E
tsmiF.Size=83, 22
tsmiF.Text=F
tsmiG.Size=83, 22
tsmiG.Text=G
tsmiH.Size=83, 22
tsmiH.Text=H
tsmiI.Size=83, 22
tsmiI.Text=I
tsmiJ.Size=83, 22
tsmiJ.Text=J
type設定ToolStripMenuItem.Size=172, 22
type設定ToolStripMenuItem.Text=Set type
toolStripSeparator5.Size=169, 6
tsmiPlayThis.Size=172, 22
tsmiPlayThis.Text=Play this music
tsmiDelThis.Size=172, 22
tsmiDelThis.Text=Remove this music
toolStripSeparator3.Size=169, 6
tsmiDelAllMusic.Size=172, 22
tsmiDelAllMusic.Text=Remove all musics
tsmiOpenFolder.Size=172, 22
cmsPlayList.Size=173, 126
dgvList.Size=585, 245
toolStripContainer1.ContentPanel.Size=585, 245
toolStripContainer1.Location=0, 0
toolStripContainer1.Size=585, 270
toolStripContainer1.Text=toolStripContainer1
tsbOpenPlayList.Size=23, 22
tsbOpenPlayList.Text=プレイリストファイルを開く
tsbSavePlayList.Size=23, 22
tsbSavePlayList.Text=プレイリストファイルを保存
toolStripSeparator1.Size=6, 25
tsbAddMusic.Size=23, 22
tsbAddMusic.Text=曲を追加
tsbAddFolder.Size=23, 22
tsbAddFolder.Text=フォルダー内の曲を追加
toolStripSeparator2.Size=6, 25
tsbUp.Size=23, 22
tsbUp.Text=上の曲と入れ替える
tsbDown.Size=23, 22
tsbDown.Text=下の曲と入れ替える
toolStripSeparator4.Size=6, 25
tsbJapanese.Size=23, 22
tsbJapanese.Text=日本語
toolStripSeparator6.Size=6, 25
tsbTextExt.Size=23, 22
tsbTextExt.Text=toolStripButton1
tsbMMLExt.Size=23, 22
tsbMMLExt.Text=toolStripButton2
tsbImgExt.Size=23, 22
tsbImgExt.Text=toolStripButton3
toolStrip1.Location=0, 0
toolStrip1.Size=585, 25
$this.AutoScaleDimensions=6, 12
$this.ClientSize=585, 270
$this.MinimumSize=400, 120
$this.Text=play list
